name: Pack extensions
on:
  workflow_dispatch:
jobs:
  pack-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pack
            VERSION

      - name: Set up version
        run: |
          VERSION=$(cat VERSION)
          echo $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Pack extension
        run: |
          cd pack && zip -r biskuvi.zip *  && cd ..
          mv pack/biskuvi.zip biskuvi-${{ env.VERSION }}.zip          
          chrome --pack-extension=pack
          mv pack.crx biskuvi-${{ env.VERSION }}.crx

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: biskuvi-extension
          if-no-files-found: error
          compression-level: 9
          path: |
            biskuvi-${{ env.VERSION }}.crx
            biskuvi-${{ env.VERSION }}.zip
