name: Pack and release
on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pack
            VERSION

      - name: Set up version
        run: |
          VERSION=$(cat VERSION)
          echo $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Pack extension
        run: |
          cd pack && zip -r biskuvi.zip *  && cd ..
          mv pack/biskuvi.zip biskuvi-${{ env.VERSION }}.zip
          sha256sum biskuvi-${{ env.VERSION }}.zip > biskuvi-${{ env.VERSION }}.zip.sha256.txt
          chrome --pack-extension=pack
          mv pack.crx biskuvi-${{ env.VERSION }}.crx
          sha256sum biskuvi-${{ env.VERSION }}.crx > biskuvi-${{ env.VERSION }}.crx.sha256.txt

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            biskuvi-${{ env.VERSION }}.crx
            biskuvi-${{ env.VERSION }}.crx.sha256.txt
            biskuvi-${{ env.VERSION }}.zip
            biskuvi-${{ env.VERSION }}.zip.sha256.txt
